export const ADD_WISHLIST_ITEM_SUCCESS = "ADD_WISHLIST_ITEM_SUCCESS";
export const ADD_WISHLIST_ITEM_FAIL = "ADD_ITEM_FAIL";

export const REMOVE_WISHLIST_ITEM_SUCCESS = "REMOVE_WISHLIST_ITEM_SUCCESS";
export const REMOVE_WISHLIST_ITEM_FAIL = "REMOVE_WISHLIST_ITEM_FAIL";

export const GET_WISHLIST_ITEMS_SUCCESS = "GET_WISHLIST_ITEMS_SUCCESS";
export const GET_WISHLIST_ITEMS_FAIL = "GET_WISHLIST_ITEMS_FAIL";

export const EMPTY_WISHLIST_SUCCESS = "EMPTY_WISHLIST_SUCCESS";
export const EMPTY_WISHLIST_FAIL = "EMPTY_WISHLIST_FAIL";

export const UPDATE_WISHLIST_ITEM_SUCCESS = "UPDATE_WISHLIST_ITEM_SUCCESS";
export const UPDATE_WISHLIST_ITEM_FAIL = "UPDATE_WISHLIST_ITEM_FAIL";
